### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by ghost** [timvisee/update-proton-ge#1]
Installing...
tar: /home/insert name here/.steam/compatibilitytools.d: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

insert @ insert:~$ 

might be because it tried to install same version I had, unless it needs sudo?

**Comment by timvisee** [comment]
Thanks for the report!

Have you installed any custom Proton version before?  
Also, where is your `.steam` directory located (is it at `~/.steam`)?

> might be because it tried to install same version I had, unless it needs sudo?

It checks for this, and shows an 'already installed' message in that case.

It looks like `~/.steam/compatibilitytools.d/` doesn't exist. I did assume this always exists on that location during the creation of this script.

**Comment by timvisee** [comment]
I was using the wrong directory, and it doesn't always exist. This has now been fixed in https://github.com/timvisee/update-proton-ge/commit/8f0c94ac498efd2604a1af99f883b358f7a2e190.

Sorry for the inconvenience.
